### ISSUE TITLE
MP3s unable to properly load on monochrome.flp

### ISSUE THREAD

**Issue by Matty005** [NoahWantsDie/fnf-shits#17]
I'm struggling with a kind of peculiar issue, where basically all mp3s inside the monochrome.flp get loaded with no sound at all.
I'm looking forward to hear a response.

**Comment by meeptey2** [comment]
use something like audacity to export them as another format, then replace each audio file in each audio channel with the converted equivalent.

**Comment by NoahWantsDie** [comment]
it because its loading a flp without the audio files inside, just drag in the inst file from the game for it to work and make your own jumpscare sound or cut it from the voices file

**Comment by Matty005** [comment]
I guess, I'll do it like that. Thanks for the help Noah.
